################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/getting-started.md
    open: true
- sections:
  - title: API Reference
    sections:
    - title: Release Notes
      link: docs/Release-Notes/Release-Notes.md
    - title: Customer Management
      sections:
      - title: Add Customer
        link: docs/APIs/Customer-Management/Add-Customer.md
      - title: Update Customer
        link: docs/APIs/Customer-Management/Update-Customer.md
      - title: Inquire DemographicData
        link: docs/APIs/Customer-Management/Inquire-Demographic-Data.md
    - title: Account Management
      sections:
      - title: Block / Unblock Account
        link: docs/APIs/Account-Management/Block-Unblock-Account.md
      - title: Update Credit limit
        link: docs/APIs/Account-Management/Update-Credit-Limit.md
      - title: Account transfer promotional product upgrade
        link: docs/APIs/Account-Management/Account-transfer-promotional-product-upgrade.md
      - title: Find Account Number
        link: docs/APIs/Account-Management/Find-Account-Number.md
    - title: Card Management
      sections:
      - title: Get Card Details
        link: docs/APIs/Card-Management/Get-Card-Details.md
      - title: Update Card or Plastic record
        link: docs/APIs/Card-Management/Update-Card-or-Plastic-record.md
      - title: Activate Card
        link: docs/APIs/Card-Management/Activate-Card.md
      - title: Update spending limits
        link: docs/APIs/Card-Management/Update-spending-limits.md
      - title: Update Card transfer
        link: docs/APIs/Card-Management/Update-Card-Transfer.md
      - title: Inquire Card or PAN token
        link: docs/APIs/Card-Management/Inquire-Card-or-PAN-token.md
      - title: Inquire security values
        link: docs/APIs/Card-Managment/Inquire-security-values.md
      - title: Card PIN change
        link: docs/APIs/Card-Managment/Card-PIN-change.md