################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
- sections:
  - title: Getting Started
    link: docs/getting-started.md
    open: true
- sections:
  - title: API Reference
    link:
    open: true
    sections:    
    - title: Account Management
      sections:
      - title: Block-Unblock Account
        link: docs/APIs/Account-Management/Block-Account.md
      - title: List Accounts' Transactions
        link: docs/APIs/Account-Management/List Accounts' Transactions.md
    - title: Card Management
      sections:
      - title: Activate Card
        link: docs/APIs/Card-Management/Activate-Card.md
      - title: Block-Unblock Card
        link: docs/APIs/Card-Management/Block-Card.md
      - title: CardType Update
        link: docs/APIs/Card-Management/CardType-Update.md
      - title: CVV2 Validation
        link: docs/APIs/Card-Management/CVV2-Validation.md
      - title: Fetch Clear PAN from Token
        link: docs/APIs/Card-Management/Fetch-Clear-PAN-from-Token.md
      - title: Lost Stolen Card Transfer
        link: docs/APIs/Card-Management/Lost-Stolen-Card-Transfer.md
      - title: PIN Block Change
        link: docs/APIs/Card-Management/PIN-Block-Change.md      
      - title: Spend Limit Updates
        link: docs/APIs/Card-Management/Spend-limit-Updates.md
    - title: Customer Management
      sections:
      - title: Customer Demographic Inquiry
        link: docs/APIs/Customer-Management/Customer-Demographic-Inquiry.md    
      - title: Customer Demographic Update
        link: docs/APIs/Customer-Management/Customer-Demographic-Update.md
      - title: List Customers' Accounts
        link: docs/APIs/Customer-Management/List Customers' Accounts.md
      - title: List Customers' Cards
        link: docs/APIs/Customer-Management/List Customers' Cards.md