################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
- sections:
  - title: Developer Studio overview
    sections:
    - title: About Developer Studio
      link: docs/about-developer-studio.md
    - title: Explore a product area
      link: docs/explore-a-product-area.md
    - title: Dive into a product
      link: docs/dive-into-a-product.md
    - title: Explore Documentation
      link: docs/explore-documentation.md
    - title: Try out the API Sandbox
      link: docs/try-out-the-api-sandbox.md
    - title: Search and All APIs
      link: docs/search-and-all-apis.md
    - title: Markdown Support
      sections:
      - title: Basic Syntax
        link: docs/md/basic-syntax.md
      - title: Extended Syntax
        link: docs/md/extended-syntax.md
- sections:
  - title: API Glossary
    link: docs/api-glossary.md
- sections:
  - title: FAQ
    link: docs/FAQ.md
- sections:
  - title: Release notes
    sections:
    - title: March 2022
      link: docs/release-notes/2022/march.md
    - title: February 2022
      link: docs/release-notes/2022/february.md
    - title: January 2022
      link: docs/release-notes/2022/january.md
- sections:
  - title: Terms of Use
    sections:
    - title: Latest
      link: docs/terms-of-use/latest.md
    - title: August 2015
      link: docs/terms-of-use/august-2015.md
- sections:
  - title: Privacy Notice
    sections:
    - title: Latest
      link: docs/privacy-notice/latest.md
    - title: June 2021
      link: docs/privacy-notice/june-2021.md
