- sections:
  - title: Getting Started
    link: /docs/getting-started.md
    open: false
    articles:
      - title: Welcome to Reporting
        link: /docs/getting-started.md
- sections:
  - title: Security
    open: false
    sections:
    - title: API Keys
      link: docs/Security/security.md